"use client";

import React from "react";
import { motion } from "framer-motion";
import { ArrowLeft, Clock, ArrowRight } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  GlassNav,
  DarkSection,
  PillButton,
  Badge,
  CanvasBackground,
} from "@/components/keystone";

// ─────────────────────────────────────────────────────────────
// POST DATA
// ─────────────────────────────────────────────────────────────
type Post = {
  slug: string;
  tag: string;
  tagVariant: "teal" | "violet" | "amber" | "ghost";
  title: string;
  excerpt: string;
  readTime: string;
  date: string;
  author: { name: string; role: string };
  body: string[];
};

const POSTS: Record<string, Post> = {
  "why-zero-auto-send": {
    slug: "why-zero-auto-send",
    tag: "Philosophy",
    tagVariant: "violet",
    title: "Why we made zero auto-send an architectural guarantee, not a setting",
    excerpt:
      "Every AI email tool promises you'll stay in control. Most don't mean it. Here's why we built the constraint into the system rather than the preferences panel.",
    readTime: "5 min",
    date: "Feb 18, 2026",
    author: { name: "Aisha Okafor", role: "Co-founder & CEO" },
    body: [
      "When we set out to build Keystone, the most common piece of advice we received was: 'Just add a confirmation dialog.' Add a modal before sending. Show a summary. Give the user a chance to cancel. Plenty of tools do this. We chose not to.",
      "The reason is subtle but important: a confirmation dialog is a UI pattern. It can be bypassed, dismissed, or — more likely — become muscle memory. When something appears every time you take an action, you stop reading it. You start clicking through it. The protection evaporates.",
      "We wanted something stronger. We wanted a system where the question 'did this send automatically?' had a provably correct answer: no.",
      "So we architected Keystone around a queue. Every draft — whether generated by AI or by you — lands in an outbox that requires an explicit, intentional dispatch action. The dispatch path is separated from the draft path at the infrastructure level. There is no way for a draft to transition to 'sent' without traversing a human-controlled gate.",
      "This has consequences for how we build features. Some things that feel natural in other AI tools are simply not possible in Keystone. You can't ask Keystone to 'send this for me' and have it execute without your review. You can ask Keystone to 'draft this for me and queue it for my review at 9 AM.' That's a meaningful distinction.",
      "We get pushback on this occasionally. 'What if I want to fully automate my follow-ups?' Our answer: we support full automation for non-email actions — CRM updates, Slack messages, calendar events. But for email specifically, we believe the risk of a miscalibrated AI sending something you didn't intend is too high, too often, to be worth the marginal convenience.",
      "Trust is built slowly and lost quickly. We'd rather be the email tool you trust completely than the one that occasionally does exactly what you'd have wanted — except for the one time it didn't.",
      "Zero auto-send isn't a feature. It's a commitment.",
    ],
  },
  "inbox-zero-myth": {
    slug: "inbox-zero-myth",
    tag: "Productivity",
    tagVariant: "teal",
    title: "Inbox zero is the wrong goal. Here's what to optimize for instead.",
    excerpt:
      "The obsession with empty inboxes has produced a generation of productivity theater. We built Keystone around a different north star: decision clarity.",
    readTime: "7 min",
    date: "Feb 10, 2026",
    author: { name: "Priya Sundaram", role: "Head of Growth" },
    body: [
      "Inbox zero is seductive because it's measurable. You can see when you've achieved it: the count hits 0, the screen is clear, you feel productive. The problem is that the number of emails in your inbox is almost entirely uncorrelated with the quality of decisions you're making.",
      "A founder who responds to every email within 10 minutes and maintains inbox zero might be spending 4 hours a day on email — most of it low-leverage. A founder with 2,000 unread emails might be making better decisions because they've learned to ignore the noise and act only on what matters.",
      "We designed Keystone around decision clarity, not message clearance. The question we ask isn't 'how do we help you empty your inbox?' It's 'how do we help you identify, in the first 5 minutes of your day, the three things that genuinely require your attention?'",
      "In practice, this means our priority model deliberately surfaces a small number of high-signal threads rather than processing everything at once. If you have 47 emails and Keystone tells you only 3 matter today, that's not a failure to process 44 threads. That's the system working.",
      "The 44 emails get filed, labeled, or auto-responded to based on templates you've approved. But they don't interrupt your cognitive focus. They exist. They're handled. They're just not in your attention queue.",
      "The shift from inbox zero to decision clarity is also a shift from reactive to proactive. Inbox zero is reactive: you're clearing a backlog someone else created. Decision clarity is proactive: you're allocating your attention to the things that move your work forward.",
      "We won't tell you inbox zero is useless. It's a fine organizational habit. But if it's your north star, you may be optimizing for the feeling of productivity rather than the output of it. We think you deserve both.",
    ],
  },
};

// Fallback for posts not in the static data
const FALLBACK_POST: Post = {
  slug: "post",
  tag: "Keystone",
  tagVariant: "teal",
  title: "Keystone Journal",
  excerpt: "Stories, technical deep-dives, and honest writing about AI and productivity.",
  readTime: "5 min",
  date: "2026",
  author: { name: "Keystone Team", role: "Keystone" },
  body: [
    "This post is coming soon. Check back shortly — we publish every two weeks.",
    "In the meantime, explore other posts in the Keystone Journal or try the product for free.",
  ],
};

// ─────────────────────────────────────────────────────────────
// PAGE
// ─────────────────────────────────────────────────────────────
export default function BlogPostPage() {
  const params = useParams();
  const slug = typeof params.slug === "string" ? params.slug : "";
  const post = POSTS[slug] ?? { ...FALLBACK_POST, slug };

  return (
    <>
      <GlassNav />
      <main className="flex flex-col bg-black text-white overflow-x-hidden">
        {/* Hero */}
        <section className="relative pt-32 pb-12 overflow-hidden bg-black">
          <div className="aurora-blob aurora-teal" />
          <CanvasBackground variant="grid" />

          <div className="relative z-10 max-w-[800px] mx-auto px-6 md:px-10">
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="mb-6"
            >
              <Link
                href="/blog"
                className="inline-flex items-center gap-1.5 text-white/40 text-sm hover:text-white/70 transition-colors"
              >
                <ArrowLeft className="w-3.5 h-3.5" />
                Back to Journal
              </Link>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.08 }}
            >
              <div className="flex items-center gap-3 mb-5">
                <Badge variant={post.tagVariant} size="sm">{post.tag}</Badge>
                <span className="text-white/25 text-xs flex items-center gap-1">
                  <Clock className="w-3 h-3" /> {post.readTime}
                </span>
                <span className="text-white/25 text-xs">{post.date}</span>
              </div>

              <h1 className="text-3xl md:text-[48px] font-bold text-white leading-tight tracking-tight mb-6">
                {post.title}
              </h1>

              <p className="text-white/50 text-lg leading-relaxed mb-8">{post.excerpt}</p>

              <div className="flex items-center gap-3 pt-5 border-t border-white/[0.08]">
                <div className="w-9 h-9 rounded-full bg-gradient-to-br from-teal-600 to-violet-700" />
                <div>
                  <div className="text-white text-sm font-semibold">{post.author.name}</div>
                  <div className="text-white/35 text-xs">{post.author.role}</div>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Article body */}
        <section className="max-w-[800px] mx-auto px-6 md:px-10 py-8">
          <div className="space-y-7">
            {post.body.map((paragraph, i) => (
              <motion.p
                key={i}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.04 }}
                className="text-white/65 leading-[1.85] text-base md:text-lg"
              >
                {paragraph}
              </motion.p>
            ))}
          </div>
        </section>

        {/* CTA */}
        <DarkSection borderTop glowColor="teal">
          <div className="max-w-[800px] mx-auto">
            <div className="bg-white/[0.03] ring-1 ring-white/[0.09] rounded-[20px] p-8 flex flex-col md:flex-row items-start md:items-center gap-6">
              <div className="flex-1">
                <div className="text-white font-bold text-lg mb-1.5">Try Keystone free</div>
                <p className="text-white/45 text-sm leading-relaxed">
                  14-day free trial. No credit card. Connect your Gmail in 60 seconds and see your inbox through a different lens.
                </p>
              </div>
              <div className="flex gap-3 shrink-0">
                <PillButton variant="primary">
                  Start free <ArrowRight className="w-4 h-4" />
                </PillButton>
              </div>
            </div>

            {/* Back navigation */}
            <div className="flex items-center justify-between mt-8 pt-6 border-t border-white/[0.06]">
              <Link href="/blog" className="flex items-center gap-1.5 text-white/35 text-sm hover:text-white/70 transition-colors">
                <ArrowLeft className="w-3.5 h-3.5" /> All posts
              </Link>
              <Link href="/blog" className="flex items-center gap-1.5 text-white/35 text-sm hover:text-white/70 transition-colors">
                Next post <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>
        </DarkSection>
      </main>
    </>
  );
}
